name: Test Win/aarch64

on:
  # push:
  #   branches:
  #     - main
  #     - h5s_unlimited
  workflow_dispatch:
  
env:
  PKG: 'Rhdf5lib'

jobs:
  install-depdendencies:
    name: Install package dependencies
    runs-on: windows-2022
    
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
        
      - name: Make R library
        run: mkdir -p ${RUNNER_TEMP}/R-lib
        
      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/R-lib
          key: R_lib-Win-ARM64-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            R_lib-ARM64-${{ hashFiles('**/DESCRIPTION') }}
            R_lib-ARM64-
            
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc-version }}
          bioc-mirror: https://ftp.gwdg.de/pub/misc/bioconductor
          Ncpus: 4
          
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: Bioc - Build, Install, Check
        id: build-install-check
        uses: grimbough/bioc-actions/build-install-check@v1

